### ISSUE TITLE
Not following HF_ENDPOINT environment variable

### ISSUE THREAD

**Issue by sandro-qiang** [huggingface/hf-hub#62]
As title said. Some down stream project like text-embeddings-inference affected by this.

**Comment by theta-lin** [comment]
You can checkout #47 and #50. There is not much progress yet, unfortunately.

**Comment by Narsil** [comment]
This is not up to this library to add support for every environment variable that might exist in the HF ecosystem.

This library enables overriding or supporting all flags if necessary in downstream apps (if it doesn't, it should).
The truth is that supporting many flags through environment variables introduces bugs, weird/broken behavior that are impossible to sanitize for, simply because we cannot control when those flags are read during an app execution and are often even unknown by the lib users.

This lib enables all the behavior downstream users could want, but we're not going to choose on behalf of them.

By far the most used/demanded feature is proxying for China which is already supported by using `HTTP(S)_PROXY` environment variables which is down at the `reqwest/ureq` crates levels. This would superseed the  `HF_ENDPOINT` asked for here most likely.

If your use case isn't solved by `HTTP(S)_PROXY` please share here more details, which endpoint are you targetting instead and why it isn't possible to use those kind of proxies.

**Comment by Narsil** [comment]
Done through `::from_env` method call (which isn't the default on purpose, using environment variables should be opt-in).

https://github.com/huggingface/hf-hub/pull/85
